/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-08-10 06:57:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CreateReview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:escapeXml", org.apache.taglibs.standard.functions.Functions.class, "escapeXml", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1658114728000L));
    _jspx_dependants.put("jar:file:/Users/brian/Desktop/5200GroupProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AirbnbSeattle/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1426003870000L));
    _jspx_dependants.put("jar:file:/Users/brian/Desktop/5200GroupProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AirbnbSeattle/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1426003870000L));
    _jspx_dependants.put("jar:file:/Users/brian/Desktop/5200GroupProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AirbnbSeattle/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1426003870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<link\n");
      out.write("  href=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.css\"\n");
      out.write("  rel=\"stylesheet\"\n");
      out.write("  />\n");
      out.write("\n");
      out.write("<link\n");
      out.write("  href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\n");
      out.write("  rel=\"stylesheet\"\n");
      out.write("/>\n");
      out.write("<title>Reviews</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar navbar-expand-lg sticky-top navbar-light bg-light\">\n");
      out.write("  <!-- Container wrapper -->\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <!-- Toggle button -->\n");
      out.write("    <button\n");
      out.write("      class=\"navbar-toggler\"\n");
      out.write("      type=\"button\"\n");
      out.write("      data-mdb-toggle=\"collapse\"\n");
      out.write("      data-mdb-target=\"#navbarSupportedContent\"\n");
      out.write("      aria-controls=\"navbarSupportedContent\"\n");
      out.write("      aria-expanded=\"false\"\n");
      out.write("      aria-label=\"Toggle navigation\"\n");
      out.write("    >\n");
      out.write("      <i class=\"fas fa-bars\"></i>\n");
      out.write("    </button>\n");
      out.write("\n");
      out.write("    <!-- Collapsible wrapper -->\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("      <!-- Navbar brand -->\n");
      out.write("      <a class=\"navbar-brand mt-2 mt-lg-0\" href=\"/AirbnbSeattle\">\n");
      out.write("        Seattle Traveler\n");
      out.write("      </a>\n");
      out.write("      <!-- Left links -->\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("      	<li class=\"nav-item\">\n");
      out.write("          <a class=\"nav-link\" href=\"findusers\">Search User</a>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("      <!-- Left links -->\n");
      out.write("    </div>\n");
      out.write("    <!-- Collapsible wrapper -->\n");
      out.write("  </div>\n");
      out.write("  <!-- Container wrapper -->\n");
      out.write("</nav>\n");
      out.write("<h1 style=\"text-align:center;\">Create Host</h1>\n");
      out.write("	<form action=\"reviewcreate\" method=\"post\" class=\"container\" style=\"width:50vw; margin-top:2vw;\">\n");
      out.write("		<div class=\"form-outline mb-4\">\n");
      out.write("			\n");
      out.write("			<input id=\"userId\" name=\"userId\" class=\"form-control\" value=\"\">\n");
      out.write("			<label for=\"userId\" class=\"form-label\">UserId</label>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"form-outline mb-4\">\n");
      out.write("			\n");
      out.write("			<input id=\"username\" name=\"username\" class=\"form-control\" value=\"\">\n");
      out.write("			<label for=\"username\" class=\"form-label\">User Name</label>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"form-outline mb-4\">\n");
      out.write("			\n");
      out.write("			<input id=\"created\" name=\"created\" class=\"form-control\" value=\"\">\n");
      out.write("			<label for=\"created\" class=\"form-label\">Created (yyyy-mm-dd)</label>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"form-outline mb-4\">\n");
      out.write("			\n");
      out.write("			<input id=\"content\" name=\"content\" class=\"form-control\" value=\"\">\n");
      out.write("			<label for=\"content\" class=\"form-label\">Content</label>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"form-outline mb-4\">\n");
      out.write("			\n");
      out.write("			<input id=\"listingId\" name=\"listingId\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.listingId)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" readonly>\n");
      out.write("			<label for=\"listingId\" class=\"form-label\">ListingId</label>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"col\">\n");
      out.write("			 <button type=\"submit\" class=\"btn btn-primary btn-block\">Submit</button>\n");
      out.write("			 <br/><br/><br/>\n");
      out.write("			 <span id=\"successMessage\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messages.success}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></span>\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("</body>\n");
      out.write("<script\n");
      out.write("  type=\"text/javascript\"\n");
      out.write("  src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.js\"\n");
      out.write("></script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
