/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-08-10 00:40:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CreateNewListing_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:escapeXml", org.apache.taglibs.standard.functions.Functions.class, "escapeXml", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1658114728000L));
    _jspx_dependants.put("jar:file:/Users/brian/Desktop/5200GroupProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AirbnbSeattle/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1426003870000L));
    _jspx_dependants.put("jar:file:/Users/brian/Desktop/5200GroupProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AirbnbSeattle/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1426003870000L));
    _jspx_dependants.put("jar:file:/Users/brian/Desktop/5200GroupProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AirbnbSeattle/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1426003870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>NewListing</title>\n");
      out.write("<link\n");
      out.write("  href=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.css\"\n");
      out.write("  rel=\"stylesheet\"\n");
      out.write("  />\n");
      out.write("\n");
      out.write("<link\n");
      out.write("  href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\n");
      out.write("  rel=\"stylesheet\"\n");
      out.write("/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar navbar-expand-lg sticky-top navbar-light bg-light\">\n");
      out.write("	  <!-- Container wrapper -->\n");
      out.write("	  <div class=\"container-fluid\">\n");
      out.write("	    <!-- Toggle button -->\n");
      out.write("	    <button\n");
      out.write("	      class=\"navbar-toggler\"\n");
      out.write("	      type=\"button\"\n");
      out.write("	      data-mdb-toggle=\"collapse\"\n");
      out.write("	      data-mdb-target=\"#navbarSupportedContent\"\n");
      out.write("	      aria-controls=\"navbarSupportedContent\"\n");
      out.write("	      aria-expanded=\"false\"\n");
      out.write("	      aria-label=\"Toggle navigation\"\n");
      out.write("	    >\n");
      out.write("	      <i class=\"fas fa-bars\"></i>\n");
      out.write("	    </button>\n");
      out.write("	\n");
      out.write("	    <!-- Collapsible wrapper -->\n");
      out.write("	    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("	      <!-- Navbar brand -->\n");
      out.write("	      <a class=\"navbar-brand mt-2 mt-lg-0\" href=\"/AirbnbSeattle\">\n");
      out.write("	        Seattle Traveler\n");
      out.write("	      </a>\n");
      out.write("	      <!-- Left links -->\n");
      out.write("	      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("	 		<li class=\"nav-item\">\n");
      out.write("	          <a class=\"nav-link\" href=\"findhosts\">FindHost</a>\n");
      out.write("	        </li>\n");
      out.write("	      </ul>\n");
      out.write("	      <!-- Left links -->\n");
      out.write("	    </div>\n");
      out.write("	    <!-- Collapsible wrapper -->\n");
      out.write("	  </div>\n");
      out.write("	  <!-- Container wrapper -->\n");
      out.write("	</nav>\n");
      out.write(" <h1 style=\"text-align:center;\">Create new Airbnb Listing</h1>\n");
      out.write(" <form action=\"listingCreate\" method=\"post\">\n");
      out.write("  <!-- 2 column grid layout with text inputs for the first and last names -->\n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("        <input type=\"text\" id=\"propertyName\" class=\"form-control\" name=\"propertyName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.propertyName)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required/>\n");
      out.write("        <label class=\"form-label\" for=\"propertyName\">Property Name</label>\n");
      out.write("        <div class=\"invalid-feedback\">Please enter the property name</div>\n");
      out.write("      </div>\n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("        <input type=\"text\" id=\"listing_url\" class=\"form-control\" name=\"listing_url\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.listing_url)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required />\n");
      out.write("        <label class=\"form-label\" for=\"listing_url\">Listing URL</label>\n");
      out.write("        <div class=\"invalid-feedback\">Please enter the listing url </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("  <!-- Text input -->\n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"picture_url\" class=\"form-control\" name=\"picture_url\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.picture_url)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required />\n");
      out.write("    <label class=\"form-label\" for=\"picture_url\">Picture URL</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the picture url </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Text input -->\n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"latitude\" class=\"form-control\" name=\"latitude\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.latitude)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required />\n");
      out.write("    <label class=\"form-label\" for=\"latitude\" >Latitude</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the latitude </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Email input -->\n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"longitude\" class=\"form-control\" name=\"longitude\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.longitude)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required />\n");
      out.write("    <label class=\"form-label\" for=\"longitude\" >longitude</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the longitude </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Number input -->\n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"property_type\" class=\"form-control\" name=\"property_type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.property_type)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required />\n");
      out.write("    <label class=\"form-label\" for=\"property_type\">Property Type</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the property type </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"room_type\" class=\"form-control\" name=\"room_type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.room_type)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required />\n");
      out.write("    <label class=\"form-label\" for=\"room_type\">Room Type</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the room type </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"accommdates\" class=\"form-control\" name=\"accommodates\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.accommodates)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required />\n");
      out.write("    <label class=\"form-label\" for=\"accommodates\">Accommodates</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the accommodates number</div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"bathrooms\" class=\"form-control\" name=\"bathrooms\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.bathrooms)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required />\n");
      out.write("    <label class=\"form-label\" for=\"bathrooms\">Bathrooms</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the bathrooms count </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"bedrooms\" class=\"form-control\" name=\"bedrooms\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.bedrooms)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required/>\n");
      out.write("    <label class=\"form-label\" for=\"bedrooms\">Bedrooms</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the bedrooms count </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"beds\" class=\"form-control\" name=\"beds\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.beds)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required />\n");
      out.write("    <label class=\"form-label\" for=\"beds\">Beds</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the bed counts </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"price\" class=\"form-control\" name=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.price)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required />\n");
      out.write("    <label class=\"form-label\" for=\"price\">Price</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the price value </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <input type=\"text\" id=\"hostId\" class=\"form-control\" name=\"hostId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.hostId)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" readonly/>\n");
      out.write("    <label class=\"form-label\" for=\"hostId\">Host Id</label>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("  <label class=\"form-label\" for=\"neighborhoodId\">Neighborhood</label>\n");
      out.write("  	<select class=\"select\" name=\"neighborhoodId\" class=\"select\">\n");
      out.write("  	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  	</select>\n");
      out.write("    ");
      out.write("\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <textarea class=\"form-control\" id=\"neighborhood_Overview\" rows=\"4\" name=\"neighborhood_Overview\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.neighborhood_Overview)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required></textarea>\n");
      out.write("    <label class=\"form-label\" for=\"neighborhood_Overview\">Neighborhood Overview</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the neighborhood overview </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Message input -->\n");
      out.write("  <div class=\"form-outline mb-4\">\n");
      out.write("    <textarea class=\"form-control\" id=\"description\" rows=\"4\" name=\"description\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(param.description)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" required></textarea>\n");
      out.write("    <label class=\"form-label\" for=\"description\">Description</label>\n");
      out.write("    <div class=\"invalid-feedback\">Please enter the property description </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Submit button -->\n");
      out.write("  <div class=\"col\">\n");
      out.write("	 <button type=\"submit\" class=\"btn btn-primary btn-block\">Submit</button>\n");
      out.write("	 <br/><br/><br/>\n");
      out.write("	 <span id=\"successMessage\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messages.success}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></span>\n");
      out.write("</div>\n");
      out.write("</form>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("<script\n");
      out.write("  type=\"text/javascript\"\n");
      out.write("  src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.js\"\n");
      out.write("></script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /CreateNewListing.jsp(143,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/CreateNewListing.jsp(143,3) '${neighborhoods}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${neighborhoods}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /CreateNewListing.jsp(143,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("neighborhood");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("  		<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${neighborhood.getNeighborhoodId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</option>\n");
            out.write("  	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /CreateNewListing.jsp(144,56) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${neighborhood.getNeighborhoodName()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
